### ISSUE TITLE
Typo's

### ISSUE THREAD

**Issue by rjbt** [Microsoft/windows-itpro-docs#172] opened 2017-04-26 17:41 UTC
In step 4 of the prerequisites you say you are installing SQL 2012 when in fact you are installing SQL 2014

**Comment by eross-msft** [comment] 2017-04-26 20:55
Which topic are you referencing?

**Comment by rjbt** [comment] 2017-04-26 21:13
[cid:image002.jpg@01D2BE97.43CCF390]

Robert Tichelman
Microsoft Canada | Premier Field Engineer (PFE) – System Center Configuration Manager | Vancouver, BC
robtich@microsoft.com<mailto:robtich@microsoft.com> | Cell: 778.387.2646 VoIP: 604.693.7926

**Comment by eross-msft** [comment] 2017-04-27 15:56
@rjbt 
I'm not seeing an actual image, just text. Can you just include the URL to the page? Or even just the topic title?

**Comment by eross-msft** [comment] 2017-05-03 14:15
Is there any update on the image or URL? Without more info I'm going to have to close this issue.

**Comment by eross-msft** [comment] 2017-05-04 14:16
@rjbt
I'm going to close this issue for now, but if you can give me more info, we can reopen this and address it.

**Comment by rjbt** [comment] 2017-05-04 14:23
I did reply to you showing the different versions of SQL being referenced. Did you not get the images?

Sent from my Windows 10 phone

**Comment by eross-msft** [comment] 2017-05-04 14:41
No. Unfortunately, all I see in here is this txt: [cid:image002.jpg@01D2BE97.43CCF390]
If you want to try to resend the images, or even just tell me the topic name with the wrong SQL reference, we can get it updated.

**Comment by apantek** [comment] 2017-05-04 18:28
Last sentence in "What if someone steals..." section. 'enablng' should say 'enabling'
![capture](https://cloud.githubusercontent.com/assets/28404821/25718969/8f7521de-30cd-11e7-896d-7000ffcd9326.PNG)

**Comment by eross-msft** [comment] 2017-05-04 19:25
@rjbt, the issue by @apantek isn't the same issue you're talking about, correct?
We can fix the "enabling" typo now, but I still need to know where to make the SQL reference fix.

**Comment by DaniHalfin** [comment] 2017-05-04 20:03
@apantek thanks for catching that one. Probably not the same issue as @rjbt found.
We've fixed that and you'll see it soon™.

**Comment by eross-msft** [comment] 2017-05-04 20:04
Thanks for doing that!

**Comment by rjbt** [comment] 2017-05-04 21:12
The problem is the version of SQL referenced in the steps 2 – 6 changes from SQL 2014 to SQL 2012 and then back to SQL 2014
[cid:image002.jpg@01D2C4F9.979F0E50]
Robert Tichelman
Microsoft Canada | Premier Field Engineer (PFE) – System Center Configuration Manager | Vancouver, BC
robtich@microsoft.com<mailto:robtich@microsoft.com> | Cell: 778.387.2646 VoIP: 604.693.7926

**Comment by eross-msft** [comment] 2017-05-04 21:15
@rjbt 
I'm still just seeing text instead of images. I'm not sure how you're trying to attach the images, but it doesn't seem to be working for some reason. Now that I understand the problem is switching back and forth between the 2 SQL versions, I can do a search of our content and try to figure it out.

**Comment by eross-msft** [comment] 2017-05-04 21:30
I believe I found where you are talking about. It's in the Install prerequisites section of the https://docs.microsoft.com/en-us/windows/deployment/windows-10-poc-sc-config-mgr topic. Correct? Assuming this is the issue, I'll get the writer to review the text and update it for the changes. Thank you!!

**Comment by rjbt** [comment] 2017-05-04 21:31
Yes that is it.

Robert Tichelman
Microsoft Canada | Premier Field Engineer (PFE) – System Center Configuration Manager | Vancouver, BC
robtich@microsoft.com<mailto:robtich@microsoft.com> | Cell: 778.387.2646 VoIP: 604.693.7926

**Comment by eross-msft** [comment] 2017-05-04 21:32
Awesome, thank you! We'll get that addressed in the topic and republished.

**Closed by eross-msft** 2017-05-04 21:32 UTC
